name: UsefulCommands
version: 1.0.0
description: Useful Commands for Server
author: noogotte
main: fr.noogotte.usefulCommands.UsefulCommandPlugin

commands:
    useful:
        description: "Commande principale."
        usage: "time | weather"
    "useful time":
        description: "Change ."
        usage: "day | night"
        permission: "useful.time"
        aliases: ["time"]

    "useful weather":
        description: "Change le temps."
        usage: "sun | storm"
        permission: "useful.weather"
        aliases: ["weather"]
permission: