name: UsefulCommands
version: 1.0.0
description: Useful Commands for Server
author: noogotte
main: fr.noogotte.useful_commands.UsefulCommandPlugin

commands:
    useful:
        description: "Commande principale."
        usage: "time | weather | gamemode | god | heal | clear | teleportation | seed | spawn"
    "useful time":
        description: "Change l'heure"
        usage: "day | night"
        permission: "useful.time"
        aliases: ["time"]
    "useful weather":
        description: "Change le temps."
        usage: "sun | storm"
        permission: "useful.weather"
        aliases: ["weather"]
    "useful gamemode":
        description: "Change le temps."
        usage: ""
        aliases: ["gm"]
    "useful god":
        description: "Met en mode dieux"
        usage: ""
        aliases: ["god"]
    "useful heal":
        description: "Soigne et nourris"
        usage: ""
        aliases: ["heal"]
    "useful clear":
        description: "Vide l'inventaire"
        usage: ""
        aliases: ["clear"]
    "useful teleportation":
        description: "Teleportation"
        usage: ""
        aliases: ["tp"]
    "useful seed":
        description: "Montre le seed du monde"
        usage: ""
        aliases: ["seed"]
    "useful spawn":
        description: "Teleport au spawn"
        usage: ""
        aliases: ["spawn"]
    "useful setspawn":
        description: "Definis au spawn"
        usage: ""
        aliases: ["setspawn"]
    "useful give":
        description: "Donne x objet"
        usage: ""
        aliases: ["give"]
    "useful open":
        description: "Ouvre l'inventaire"
        usage: ""
        aliases: ["open"]