name: UsefulCommands
version: 1.0.0
description: Useful Commands for Server
author: noogotte
main: fr.noogotte.useful_commands.UsefulCommandPlugin

# Commandes
commands:
    useful:
        description: "Commande principale."
        usage: "time | weather | gamemode | god | heal | clear | teleportation | seed | spawn"

    # World commands
    "useful seed":
        description: "Montre le seed du monde."
        usage: "[world]"
        permission: "useful.seed"
        aliases: ["seed"]
    "useful setspawn":
        description: "Definis le spawn."
        usage: ""
        permission: "useful.setspawn"
        aliases: ["setspawn"]
    "useful time":
        description: "Change l'heure."
        usage: "day | night [world]"
        permission: "useful.time"
        aliases: ["time"]
    "useful weather":
        description: "Change le temps."
        usage: "sun | storm [world]"
        permission: "useful.weather"
        aliases: ["weather"]

    # Player commands
    "useful gamemode":
        description: "Change le gamemode."
        usage: "[target]"
        permission: "useful.gamemode"
        aliases: ["gm", "gamemode"]
    "useful god":
        description: "Met en mode dieu."
        usage: "[target]"
        permission: "useful.god"
        aliases: ["god"]
    "useful heal":
        description: "Soigne et nourris."
        usage: "[-hf] [target]"
        permission: "useful.heal"
        aliases: ["heal"]
    "useful clear":
        description: "Vide l'inventaire."
        usage: "[-qra] [target]"
        permission: "useful.clear"
        aliases: ["clear"]
    "useful give":
        description: "Donne x objet."
        usage: "<type> [amount] [target]"
        permission: "useful.give"
        aliases: ["give", "i", "item"]
    "useful open":
        description: "Ouvre l'inventaire."
        usage: "[target]"
        permission: "useful.openinv"
        aliases: ["open"]
    "useful playerinfo":
        description: "Affiche les infos de la cible"
        usage: "[target]"
        permission: "useful.playerinfo"
        aliases: ["pinfo", "player-info"]
    "useful id":
        description: "Affiche l id de l objet tenus en main"
        usage: ""
        permission: "useful.id"
        aliases: ["id"]
    "useful kick":
        description: "Kick un joueure"
        usage: ""
        permission: "useful.kick"
        aliases: ["kick"]
    "useful tell":
        description: "Envoie un msg prive"
        usage: "[target]  [msg]"
        permission: "useful.tell"
        aliases: ["tell", "say"]
    "useful fly":
        description: "Mais en vole"
        usage: "[target]"
        permission: "useful.fly"
        aliases: ["fly"]
    "useful kill":
        description: "Kill"
        usage: "[target]"
        permission: "useful.kill"
        aliases: ["kill"]
    "useful effect":
        description: "Mais un effet de potion"
        usage: "[potion] [duration] [target]"
        permission: "useful.effect"
        aliases: ["effect"]
    "useful enchantment":
        description: "Enchante un objet"
        usage: "[enchantment] [level]"
        permission: "useful.enchant"
        aliases: ["enchant"]
    # Teleport commands
    "useful teleportation":
        description: "Teleportation."
        usage: "<target> | <player> <target>"
        permission: "useful.teleportation"
        aliases: ["tp"]
    "useful teleport-to":
        description: "Teleporte aux coordonnées données."
        usage: "<x>,<y>,<z> [world] [target]"
        permission: "useful.teleportto"
        aliases: ["tpto"]
    "useful spawn":
        description: "Teleport au spawn."
        usage: "[target]"
        permission: "useful.spawn"
        aliases: ["spawn"]
#¨Permissions
permissions:
    useful.tell:
        default: true
