name: UsefulCommands
version: 1.0.0
description: Useful Commands for Server
author: noogotte
main: fr.noogotte.useful_commands.UsefulCommandsPlugin

# Commandes
commands:
    useful:
        description: "Commande principale."
        usage: ""
        aliases: ["us"]

    # World commands
    "useful seed":
        description: "Montre le seed du monde."
        usage: "[world]"
        aliases: ["seed"]
        permission: "useful.world.seed"
    "useful setspawn":
        description: "Définit le spawn."
        usage: ""
        aliases: ["setspawn"]
        permission: "useful.world.setspawn"
    "useful time":
        description: "Change l'heure."
        usage: "<time> [world]"
        aliases: ["time"]
        permission: "useful.world.time"
    "useful weather":
        description: "Change le temps."
        usage: "[sun | storm] [world]"
        aliases: ["weather"]
        permission: "useful.world.weather"
    "useful spawnmob":
        description: "Spawn un ou plusieurs mob(s)."
        usage: "[-tp] [-d=<distance>] <mob...> [target]"
        aliases: ["spawnmob", "mob"]
        permission: "useful.world.spawnmob"
    "useful removemob":
        description: "Supprime un ou plusieurs mob(s)."
        usage: "<type> [radius] [-w=<world> [-c=<x,y,z>]] [-p=<player>]"
        aliases: ["removemob", "rmmob"]
        permission: "useful.world.removemob"

    # God Command
    "useful god":
        description: "Met en mode Dieu."
        usage: "[target]"
        aliases: ["god"]
        permission: "useful.god"
    "useful ungod":
        description: "Enleve le mode Dieu."
        usage: "[target]"
        aliases: ["ungod"]
        permission: "useful.ungod"

    # Afk Command
    "useful afk":
        description: "Met en afk"
        usage: "<target>"
        aliases: ["afk"]
        permission: "useful.afk"

    # Chat Commands :
    "useful tell":
        description: "Envoie un message privé."
        usage: '<target...> "<message>"'
        aliases: ["tell", "say"]
        permission: "useful.chat.tell"
    "useful reply":
        description: "Réponds à un message privé."
        usage: '"<message>"'
        aliases: ["reply", "rp", "r"]
        permission: "useful.chat.reply"
    "useful mute":
        description: "Rends muet"
        usage: "<target...>"
        aliases: ["mute"]
        permission: "useful.chat.mute"
    "useful unmute":
        description: "Rends non muet"
        usage: "<target...>"
        aliases: ["unmute"]
        permission: "useful.chat.unmute"
    "useful broadcast":
        description: "Diffuse un message"
        usage: '[-a] [-g=group] [-c=permission] "<message>"'
        aliases: ["broadcast", "br"]
        permission: "useful.chat.broadcast"
    "useful me":
        description: "Commande me"
        usage: '"<message>"'
        aliases: ["me"]
        permission: "useful.chat.me"

    # Player commands
    "useful gamemode":
        description: "Change le gamemode."
        usage: "[target]"
        aliases: ["gm", "gamemode"]
        permission: "useful.player.gamemode"
    "useful heal":
        description: "Soigne et nourrit."
        usage: "[-hf] [target]"
        aliases: ["heal"]
        permission: "useful.player.heal"
    "useful playerinfo":
        description: "Affiche les infos de la cible."
        usage: "<target>"
        aliases: ["pinfo", "player-info", "whois"]
        permission: "useful.player.info"
    "useful kick":
        description: "Kick un joueur."
        usage: "<target> [reason...]"
        aliases: ["kick"]
        permission: "useful.player.kick"
    "useful fly":
        description: "Active le vol."
        usage: "[target]"
        aliases: ["fly"]
        permission: "useful.player.fly"
    "useful kill":
        description: "Kill"
        usage: "[target]"
        aliases: ["kill"]
        permission: "useful.player.kill"
    "useful effect":
        description: "Applique un effet de potion."
        usage: "<potion> [duration = 60] [target]"
        aliases: ["effect"]
        permission: "useful.player.effect"
    "useful rename":
        description: "Renomme le joueure."
        usage: "[name] <target>"
        aliases: ["rename"]
        permission: "useful.player.rename"
    "useful burn":
        description: "Enflamme un joueur."
        usage: "[player] <duration = 10>"
        aliases: ["burn"]
        permission: "useful.player.burn"
    "useful online":
        description: "Montre la liste des joueurs"
        usage: ""
        aliases: ["who", "online"]
        permission: "useful.player.online"
    "useful operatorlist":
        description: "Montre la liste des ops"
        usage: ""
        aliases: ["oplist"]
        permission: "useful.player.oplist"
    "useful adventure":
        description: "Active le mode aventure."
        usage: "[target]"
        aliases: ["adventure"]
        permission: "useful.player.adventure"

    # Inventory Commands
    "useful clear":
        description: "Vide l'inventaire."
        usage: "[-qra] [target]"
        aliases: ["clear"]
        permission: "useful.inventory.clear"
    "useful give":
        description: "Donne x objets."
        usage: "[-e] <type> [amount] [target]"
        aliases: ["give", "i", "item"]
        permission: "useful.inventory.give"
    "useful open":
        description: "Ouvre l'inventaire."
        usage: "[target]"
        aliases: ["open"]
        permission: "useful.inventory.open"
    "useful id":
        description: "Affiche l'id de l'objet en main."
        usage: ""
        aliases: ["id"]
        permission: "useful.inventory.id"
    "useful enchantment":
        description: "Enchante un objet."
        usage: "<enchantment> [level = 1]"
        aliases: ["enchant"]
        permission: "useful.inventory.enchant"
    "useful remove-enchantment":
        description: "Supprimes un enchantment d'un objet."
        usage: "[enchantment]"
        aliases: ["removeenchant", "rmenchant"]
        permission: "useful.inventory.removeenchant"

    # Warp Commands
    "useful setwarp":
        description: "Crée un warp."
        usage: "<name>"
        aliases: ["setwarp"]
        permission: "useful.warp.set"
    "useful deletewarp":
        description: "Supprime un warp."
        usage: "<name>"
        aliases: ["deletewarp", "delwarp", "removewarp", "rmwarp"]
        permission: "useful.warp.delete"
    "useful warp":
        description: "Téléporte à un warp."
        usage: "<name> [target]"
        aliases: ["warp"]
        permission: "useful.warp.tp"
    "useful warps":
        description: "Liste les warps."
        usage: ""
        aliases: ["warps"]
        permission: "useful.warp.list"
    "useful warplocation":
        description: "Coordonnée du warp"
        usage: "<name>"
        aliases: ["warplocation", "warploc"]
        permission: "useful.warp.warplocation"

    # Kit Commands
    "useful kit":
        description: "Donne un kit."
        usage: "[-c] <name> [target...]"
        aliases: ["kit"]
        permission: "useful.kit.give"
    "useful kits":
        description: "Liste les kits disponibles."
        usage: ""
        aliases: ["kits"]
        permission: "useful.kit.list"
    "useful addkit":
        description: "Ajoute un kit."
        usage: "[-f] <name>"
        aliases: ["addkit"]
        permission: "useful.kit.add"
    "useful deletekit":
        description: "Supprime un kit."
        usage: "<name>"
        aliases: ["deletekit", "removekit", "rmkit"]
        permission: "useful.kit.remove"

    # Fun Commands
    "useful rocket":
        description: "Rocket le joueure"
        usage: "<name>"
        aliases: ["rocket"]
        permission: "useful.fun.rocket"
    "useful strike":
        description: "Envoi un éclair sur le joueur"
        usage: "<target>"
        aliases: ["strike"]
        permission: "useful.fun.strike"

    # Teleport commands
    "useful teleportation":
        description: "Téléporte à un joueur."
        usage: "<target> | <player> <target>"
        aliases: ["tp"]
        permission: "useful.teleport.teleport"
    "useful summon":
        description: "Téléporte un joueur à vous."
        usage: "[-t] [-d=<distance>] <players...> [distance]"
        aliases: ["summon", "s"]
        permission: "useful.teleport.summon"
    "useful put":
        description: "Téléporte un joueur à l'emplacement regardé."
        usage: "<targets...>"
        aliases: ["put"]
        permission: "useful.teleport.put"
    "useful teleport-to":
        description: "Téléporte aux coordonnées données."
        usage: "<x>,<y>,<z> [world] [target]"
        aliases: ["tpto"]
        permission: "useful.teleport.teleportto"
    "useful spawn":
        description: "Téléporte au spawn."
        usage: "[target...]"
        aliases: ["spawn"]
        permission: "useful.teleport.spawn"
    "useful position":
        description: "Montre la position du joueur"
        usage: "[target...]"
        aliases: ["position", "getpos", "pos"]
        permission: "useful.world.position"

    #Vanish
    "useful vanish":
        description: "Rend invisible un joueur"
        usage: "[target...]"
        aliases: ["vanish"]
        permission: "useful.vanish.command"
    "useful vanish-list":
        description: "Rend invisible un joueur"
        usage: ""
        aliases: ["vanishlist"]
        permission: "useful.vanish.command.list"

    #Spy
    "useful spy":
        description: "Met en mode espion"
        usage: "[target...]"
        aliases: ["spy"]
        permission: "useful.spy.command.spy"
    "useful spy-list":
        description: "Liste des espions"
        usage: ""
        aliases: ["spylist"]
        permission: "useful.spy.command.list"

    #Home
    "useful sethome":
        description: "Definis un home"
        aliases: ["sethome"]
        permission: "useful.home.sethome"
    "useful home":
        description: "Teleportation à son home"
        aliases: ["home"]
        permission: "useful.home.use"
    "useful deletehome":
        description: "Supprime un home"
        aliases: ["deletehome", "delhome"]
        permission: "useful.home.delhome"
    "useful homes":
        description: "Montre la liste des homes"
        aliases: ["homes"]
        permission: "useful.home.list"

    #Plugin
    "useful disable":
        description: "Désactive un plugin"
        aliases: ["disable"]
        permission: "useful.plugin.disable"
    "useful enable":
        description: "Active un plugin"
        aliases: ["enable"]
        permission: "useful.plugin.enable"
    "useful info-plugin":
        description: "Active un plugin"
        aliases: ["info-plugin"]
        permission: "useful.plugin.info-plugin"

# Permissions
permissions:
    useful.*:
        default: op
        children:
            - useful.world.*: true
            - useful.god.*: true
            - useful.afk.*: true
            - useful.player.*: true
            - useful.inventory.*: true
            - useful.warp.*: true
            - useful.kit.*: true
            - useful.fun.*: true
            - useful.teleport.*: true
            - useful.afk.*: true
            - useful.god.*: true
            - useful.vanish.*: true
            - useful.spy.*: true
            - useful.home.*: true
            - useful.plugin*: true

    useful.world.*:
        children:
            - useful.world.seed: true
            - useful.world.setspawn: true
            - useful.world.time: true
            - useful.world.time.broadcast: true
            - useful.world.weather: true
            - useful.world.weather.broadcast: true
            - useful.world.spawnmob: true
            - useful.world.removemob: true
            - useful.world.position: true
            - useful.world.position.other: true

    useful.god.*:
        children:
            - useful.god: true
            - useful.god.other: true
            - useful.ungod: true
            - useful.ungod.other: true

    useful.afk.*:
        children:
            - useful.afk: true
            - useful.afk.other: true

    useful.chat.*:
        children:
            - useful.chat.tell: true
            - useful.chat.mute: true
            - useful.chat.mute.other: true
            - useful.chat.unmute: true
            - useful.chat.unmute.other: true
            - useful.chat.broadcast: true
            - useful.chat.me: true
            - useful.chat.me.channel: true

    useful.chat.tell:
        default: true
        children:
            - useful.chat.reply: true
    useful.chat.broadcast.admin:
        default: op
    useful.chat.me:
        default: true
    useful.chat.me.channel:
        default: true

    useful.player.*:
        children:
            - useful.player.gamemode: true
            - useful.player.gamemode.other: true
            - useful.player.heal: true
            - useful.player.heal.other: true
            - useful.player.info: true
            - useful.player.kick: true
            - useful.player.fly: true
            - useful.player.fly.other: true
            - useful.player.kill: true
            - useful.player.kill.other: true
            - useful.player.effect: true
            - useful.player.effect.other: true
            - useful.player.rename: true
            - useful.player.rename.other: true
            - useful.player.burn: true
            - useful.player.burn.other: true
            - useful.player.oplist: true
            - useful.player.online: true
            - useful.player.adventure: true
            - useful.player.adventure.other: true

    useful.inventory.*:
        children:
            - useful.inventory.clear: true
            - useful.inventory.clear.other: true
            - useful.inventory.give: true
            - useful.inventory.give.other: true
            - useful.inventory.open: true
            - useful.inventory.open.notify: true
            - useful.inventory.id: true
            - useful.inventory.enchant: true
            - useful.inventory.removeenchant: true

    useful.warp.*:
        children:
            - useful.warp.set: true
            - useful.warp.delete: true
            - useful.warp.tp: true
            - useful.warp.tp.other: true
            - useful.warp.list: true
            - useful.warp.warplocation: true

    useful.kit.*:
        children:
            - useful.kit.give: true
            - useful.kit.give.other: true
            - useful.kit.list: true
            - useful.kit.add: true
            - useful.kit.remove: true

    useful.fun.*:
        children:
            - useful.fun.rocket: true
            - useful.fun.rocket.other: true
            - useful.fun.strike: true
            - useful.fun.strike.other: true

    useful.teleport.*:
        children:
            - useful.teleport.teleport: true
            - useful.teleport.teleport.other: true
            - useful.teleport.summon: true
            - useful.teleport.put: true
            - useful.teleport.put.other: true
            - useful.teleport.teleportto: true
            - useful.teleport.teleportto.other: true
            - useful.teleport.spawn: true
            - useful.teleport.spawn.other: true

    useful.vanish.*:
        children:
            - useful.vanish.command: true
            - useful.vanish.command.other: true
            - useful.vanish.command.list: true

    useful.spy.*:
        children:
            - useful.spy.command.spy: true
            - useful.spy.command.spy.other: true
            - useful.spy.command.broadcast: true
            - useful.spy.command.list: true
    useful.home.*:
        children:
            - useful.home.list: true
            - useful.home.delhome: true
            - useful.home.sethome: true
            - useful.home.use: true
            - useful.home.use.other: true
            - useful.home.delhome.other: true

    useful.home.use.other:
        default: op
    useful.home.delhome.other:
        default: op
    useful.plugin*:
        children:
            - useful.plugin.disable: true
            - useful.plugin.enable: true
            - useful.plugin.info-plugin: true
